apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  progressDeadlineSeconds: 30
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
