---
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: gws
servers: 1
agents: 0
image: docker.io/rancher/k3s:v1.30.3-k3s1
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
  - port: 8443:443
    nodeFilters:
      - loadbalancer
