import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import { PublicEnvProvider } from "next-runtime-env";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <PublicEnvProvider />
      </head>
      <body
        className={cn(
          inter.className,
          "w-screen h-screen overflow-hidden bg-background"
        )}
      >
        <div data-vaul-drawer-wrapper className="size-full bg-background">
          {children}
        </div>
        <Toaster position="top-center" closeButton richColors />
      </body>
    </html>
  );
}
