[package]
name = "openapi"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.87"
api = { path = "../../apps/api" }
clap = { version = "4.5.17", features = ["derive"] }
utoipa = { workspace = true }
